#!/bin/sh

# Uses pysilfont tools

# Produce individual UFOs from Glyphs file
psfglyphs2ufo --nofea source/Surma.glyphs source -l source/logs/glyphsexportR.log

# Continue with normal preflight
./preflight
