#!/bin/sh

# Uses pysilfont tools

# update psnames and sort order, which also normalizes it
echo "-----Normalizing UFO..."
echo "-----Fixing FF glifs..."
psffixffglifs -p checkfix=fix source/Surma-Regular.ufo -l source/logs/fixffR.log

echo "-----Updating production names..."
psfsetpsnames -p checkfix=fix -i source/glyph_data.csv source/Surma-Regular.ufo -x

echo "-----Updating glyph orders..."
psfsetglyphorder --header sort_final -i source/glyph_data.csv source/Surma-Regular.ufo -x

echo "-----Exporting anchors..."
psfexportanchors -g source/Surma-Regular.ufo source/Surma_anchors.xml -l source/logs/exportanchors.log

echo "-----Preflight completed!"
