#!/bin/sh

# Uses pysilfont tools

# Produce UFO from Glyphs file
echo "-----Producing UFO from Glyphs file..."
psfglyphs2ufo --nofea source/Surma.glyphs source

# update psnames and sort order, which also normalizes it
echo "-----Normalizing UFO..."
echo "-----Updating production names..."
psfsetpsnames -p checkfix=fix -i source/glyph_data.csv source/Surma-Regular.ufo -x

echo "-----Updating glyph orders..."
psfsetglyphorder --header sort_final -i source/glyph_data.csv source/Surma-Regular.ufo -x

# Fix problem with non-spacing marks due to glyphsLib bug
echo "-----Restoring width to non-spacing marks..."
psfremovegliflibkeys source/Surma-Regular.ufo com.schriftgestaltung.Glyphs.originalWidth  -l source/logs/widthfixR.log

echo "-----Exporting anchors..."
psfexportanchors -g source/Surma-Regular.ufo source/Surma_anchors.xml -l source/logs/exportanchors.log

echo "-----Updating woff metadata file..."
psfmakewoffmetadata -q -n "Surma" -i "uk.org.sylheti" source/Surma-Regular.ufo

echo "-----Preflight completed!"
